name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive
    - name: Install Meson
      shell: bash
      run: |
          sudo apt update
          sudo apt install python3 python3-pip python3-setuptools python3-wheel ninja-build
          pip3 install meson
    - uses: actions/checkout@v6
      with:
        repository: KindleModding/kindle-sdk
        submodules: recursive
        path: kindle-sdk
    - name: Download Kindle toolchains
      shell: bash
      run: |
            wget -q https://github.com/KindleModding/koxtoolchain/releases/latest/download/kindlepw2.tar.gz -O - | tar -xzf - -C ~
            wget -q https://github.com/KindleModding/koxtoolchain/releases/latest/download/kindlehf.tar.gz -O - | tar -xzf - -C ~
    - name: Setup kindle-sdk + dependencies
      shell: bash
      run: |
          sudo apt install -y zlib1g-dev libarchive-dev nettle-dev aria2
          bash ./kindle-sdk/gen-sdk.sh kindlepw2
          bash ./kindle-sdk/gen-sdk.sh kindlehf
    - name: Build
      shell: bash
      run: |
            meson setup --cross-file ~/x-tools/arm-kindlehf-linux-gnueabihf/meson-crosscompile.txt builddir_kindlehf --reconfigure --buildtype=release
            meson setup --cross-file ~/x-tools/arm-kindlepw2-linux-gnueabi/meson-crosscompile.txt builddir_kindlepw2 --reconfigure --buildtype=release
            meson compile -C builddir_kindlehf
            meson compile -C builddir_kindlepw2
            mkdir -p build
            mkdir -p build/kindlehf
            mkdir -p build/kindlepw2
            mv builddir_kindlehf/src/libkpm.so build/kindlehf/
            mv builddir_kindlehf/cli/kpm build/kindlehf/
            mv builddir_kindlepw2/src/libkpm.so build/kindlepw2/
            mv builddir_kindlepw2/cli/kpm build/kindlepw2/
    - name: Package
      shell: bash
      run: |
            mkdir -p package/kmc/kindlehf/bin
            mkdir -p package/kmc/kindlehf/lib
            cp build/kindlehf/libkpm.so package/kmc/kindlehf/lib/
            cp build/kindlehf/kpm package/kmc/kindlehf/bin/
            cp build/kindlehf/libkpm.so package-compat/kmc/kindlehf/lib/
            cp build/kindlehf/kpm package-compat/kmc/kindlehf/bin/
            

            mkdir -p package/kmc/kindlepw2/bin
            mkdir -p package/kmc/kindlepw2/lib
            cp build/kindlepw2/libkpm.so package/kmc/kindlepw2/lib/
            cp build/kindlepw2/kpm package/kmc/kindlepw2/bin/
            cp build/kindlepw2/libkpm.so package-compat/kmc/kindlepw2/lib/
            cp build/kindlepw2/kpm package-compat/kmc/kindlepw2/bin/
            

            python kpm-helper.py package pack package ./build/kpm_0.2.0_kindlehf-kindlepw2.kpkg
            python kpm-helper.py package pack package-compat ./build/kpm_0.2.0_kindlehf-kindlepw2-compat.kpkg --compression 0
    - uses: actions/upload-artifact@v4
      with:
        name: KPM
        path: build/