name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-26.04

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive
    - name: Install Meson
      shell: bash
      run: |
          sudo apt update
          sudo apt install gcc-15 g++-15 python3 python3-pip python3-setuptools python3-wheel ninja-build
          pip3 install meson
    - name: Build
      shell: bash
      run: |
            meson setup --reconfigure --buildtype=release builddir
            cd builddir
            meson test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: testlog.txt
        path: builddir/meson-logs/testlog.txt
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: builddir
        path: builddir